steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'infrastructure/Dockerfile.prod', '-t', 'europe-west2-docker.pkg.dev/eufunding/fondeu/app:latest', '.']
images:
  - 'europe-west2-docker.pkg.dev/eufunding/fondeu/app:latest'
options:
  machineType: 'E2_HIGHCPU_8'
